Dev
Mahmoudgalalz/crcl pull request #92
Opened 2024-12-19 18:34 UTC by AmrTamer23

2024-12-19 18:41 UTC, Mahmoudgalalz approved these changes

2024-12-24 16:42 UTC, Mahmoudgalalz requested changes

2024-12-24 16:42 UTC, Mahmoudgalalz commented on src/components/event/ticket-reqs/send-invitaion-modal.tsx
> +        ...(data.type === "free" ? {} : { ticketId: data.ticketId }),
We need to change Family to  Invitation Lounge,

And make sure to capitalize first I

2024-12-24 16:42 UTC, Mahmoudgalalz commented on src/components/event/ticket-reqs/send-invitaion-modal.tsx
> +                          Family and Friends
Here

2024-12-24 16:42 UTC, Mahmoudgalalz commented on src/components/login-form.tsx
> +
Very bad and has a lot of issues

2024-12-24 17:31 UTC, AmrTamer23 commented on src/components/login-form.tsx
> +
I know but to enhance this we need an endpoint to verify on the backend, can I work on it? Or do you have a better approach?

2024-12-24 19:11 UTC, merged